# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.agent:
    image: wazuh/wazuh-agent:4.14.1
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER=172.25.0.222
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      - wazuh_net

networks:
  wazuh_net:
    external: true
    name: multi-node_wazuh-net