apiVersion: "v1"
protocol: "ssh"
address: ":22"
description: "SSH Interactive Terminal"
commands:
  - regex: "^ls$"
    handler: "Documents  Images  Desktop  Downloads  .m2  .kube  .ssh  .docker"
  - regex: "^pwd$"
    handler: "/home/ubuntu"
  - regex: "^uname -m$"
    handler: "x86_64"
  - regex: "^docker ps$"
    handler: "CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES"
  - regex: "^uname$"
    handler: "Linux"
  - regex: "^whoami$"
    handler: "ubuntu"
  - regex: "^(.+)$"
    handler: "command not found"
serverVersion: "OpenSSH_8.2p1 Ubuntu-4ubuntu0.5"
serverName: "ubuntu"
passwordRegex: "^(root|qwerty|123456|password|admin)$"
deadlineTimeoutSeconds: 60

---
apiVersion: "v1"
protocol: "http"
address: ":80"
description: "Wordpress 6.2"
commands:
  - regex: "^(/index.php|/index.html|/)$"
    handler: |
      <html>
      <head><title>Wordpress 6.2 test page</title></head>
      <body>
      <h1>Welcome to my WordPress site</h1>
      <p>This is a temporary landing page while the main site is under maintenance.</p>
      </body>
      </html>
    headers:
      - "Content-Type: text/html"
      - "Server: Apache/2.4.52 (Ubuntu)"
      - "X-Powered-By: PHP/8.1.2"
    statusCode: 200
  - regex: "^(/wp-login.php|/wp-admin)$"
    handler: |
      <html>
      <head><title>WordPress > Log In</title></head>
      <body>
      <form action="" method="post">
      <label for="user_login">Username</label><input type="text" name="log" id="user_login">
      <label for="user_pass">Password</label><input type="password" name="pwd" id="user_pass">
      <input type="submit" name="wp-submit" id="wp-submit" value="Log In">
      </form>
      </body>
      </html>
    headers:
      - "Content-Type: text/html"
      - "Server: Apache/2.4.52 (Ubuntu)"
    statusCode: 200
  - regex: "^.*$"
    handler: "<html><h1>404 Not Found</h1></html>"
    headers:
      - "Content-Type: text/html"
    statusCode: 404
